# 这里只保留社交媒体菜单

main:
  - identifier: home
    name: 首页
    url: /
    weight: 1
    params:
      icon: home

  - identifier: archives
    name: 归档
    url: /archives/
    weight: 2
    params:
      icon: archives

  - identifier: links
    name: 友链
    url: /links/
    weight: 3
    params:
      icon: link

  - identifier: about
    name: 关于
    url: /about/
    weight: 4
    params:
      icon: user

  - identifier: search
    name: 搜索
    url: /search/
    weight: 5
    params:
      icon: search

social:  # 社交媒体菜单
    - identifier: github  # 标识符
      name: GitHub  # 显示名称
      weight: 1
      url: https://github.com/z1HwanG/Blog_Test  # 链接URL
      params:
        icon: brand-github  # 图标名称
    - identifier: e-mail
      name: E-mail
      weight: 2
      url: mailto:z1hwang@163.com
      params:
        icon: mail
    - identifier: bilibili
      name: bilibili
      weight: 3
      url: https://space.bilibili.com/22311089
      params:
        icon: brand-bilibili
    - identifier: douban
      name: Douban
      weight: 4
      url: https://www.douban.com/people/z1HwanG
      params:
        icon: brand-douban